services:
  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: evently
      POSTGRES_PASSWORD: evently

    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/evently
      SPRING_DATASOURCE_USERNAME: evently
      SPRING_DATASOURCE_PASSWORD: evently